function cellInfo = Airframe_Cmd_Bus(varargin)
% AIRFRAME_CMD_BUS returns a cell array containing bus object information
%
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
%                 when the MATLAB file is executed.
% The order of bus element attributes is as follows:
%   ElementName, Dimension, DataType, SampleTime, Complexity, SamplingMode, Min, Max, DocUnits, Description

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
    suppressObject = true;
elseif nargin > 1
    error('Invalid input argument(s) encountered');
end

cellInfo = { ...
  { ...
    'Airframe_Cmd_Bus', ...
    '', ...
    '', ...
    'Auto', ...
    '-1', { ...
        {'Guidance_Cmd', 1, 'Guidance_Cmd_Bus', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'Controller_Cmd', 1, 'Controller_Cmd_Bus', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'ATT_Cmd', 1, 'ATT_Cmd_Bus', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'Control_Surface_Cmd', 1, 'Control_Surface_Cmd_Bus', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'Servo_Cmd', 1, 'Servo_Cmd_Bus', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
          } ...
  } ...
}';


if ~suppressObject
    % Create bus object in the MATLAB workspace
    Simulink.Bus.cellToObject(cellInfo)
end


% ------- EOF -------