function cellInfo = FDM_States_Bus(varargin)
% FDM_STATES_BUS returns a cell array containing bus object information
%
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
%                 when the MATLAB file is executed.
% The order of bus element attributes is as follows:
%   ElementName, Dimension, DataType, SampleTime, Complexity, SamplingMode, Min, Max, DocUnits, Description

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
    suppressObject = true;
elseif nargin > 1
    error('Invalid input argument(s) encountered');
end

cellInfo = { ...
  { ...
    'FDM_States_Bus', ...
    '', ...
    '', ...
    'Auto', ...
    '-1', { ...
        {'Attitude_States', 1, 'ATT_Euler_Bus', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'Translation_States', 1, 'Translation_States_Bus', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'Position_States', 1, 'Position_States_Bus', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'Airframe_States', 1, 'Airframe_States_Bus', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
          } ...
  } ...
}';


if ~suppressObject
    % Create bus object in the MATLAB workspace
    Simulink.Bus.cellToObject(cellInfo)
end


% ------- EOF -------