function cellInfo = Simulation_Ctrl_Bus(varargin)
% SIMULATION_CTRL_BUS returns a cell array containing bus object information
%
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
%                 when the MATLAB file is executed.
% The order of bus element attributes is as follows:
%   ElementName, Dimension, DataType, SampleTime, Complexity, SamplingMode, Min, Max, DocUnits, Description

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
    suppressObject = true;
elseif nargin > 1
    error('Invalid input argument(s) encountered');
end

cellInfo = { ...
  { ...
    'Simulation_Ctrl_Bus', ...
    '', ...
    '', ...
    'Auto', ...
    '-1', { ...
        {'run', 1, 'boolean', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'reset', 1, 'boolean', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'FDM_Ctrl', 1, 'FDM_Ctrl_Bus', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'HW_Ctrl', 1, 'HW_Ctrl_Bus', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'FCC_Ctrl', 1, 'FCC_Ctrl_Bus', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'COM_Ctrl', 1, 'COM_Ctrl_Bus', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'realtime', 1, 'boolean', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'external', 1, 'boolean', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'heartbeat', 1, 'uint16', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
          } ...
  } ...
}';


if ~suppressObject
    % Create bus object in the MATLAB workspace
    Simulink.Bus.cellToObject(cellInfo)
end


% ------- EOF -------